// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "space ship":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 1 1 1 1 f . . . . . . 
. . . . 1 2 8 1 . . . . . . . . 
. . . 1 1 2 4 1 . . . . . . . . 
. . 1 4 1 2 4 8 1 . . . . . . . 
. . 1 4 1 2 4 2 8 1 1 1 . . . . 
. . 1 4 1 2 4 2 8 6 6 9 1 . . . 
. . 1 4 1 2 4 2 8 1 1 1 . . . . 
. . 1 4 1 2 4 8 1 . . . . . . . 
. . . 1 1 2 4 1 . . . . . . . . 
. . . . 1 2 8 1 . . . . . . . . 
. . . . . 1 1 1 1 f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "mega":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . 2 2 2 2 2 . . . . . . 
. . . . 2 2 4 4 4 2 2 . . . . . 
. . . . 2 5 5 5 4 4 2 2 . . . . 
. . . 2 2 5 4 4 5 5 5 2 . . . . 
. . . . 2 5 5 5 4 4 2 2 . . . . 
. . . . 2 2 4 4 4 2 2 . . . . . 
. . . . . 2 2 2 2 2 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "bala":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 2 2 2 2 2 2 . . . . . . 
. . . 2 2 2 4 4 4 2 . . . . . . 
. . . 2 5 5 5 5 4 2 2 2 . . . . 
. . . 2 5 5 4 5 5 5 5 2 . . . . 
. . . 2 5 5 5 5 4 2 2 2 . . . . 
. . . 2 2 2 4 4 4 2 2 2 . . . . 
. . . . . 2 2 2 2 2 . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image4":
            case "boss":return img`
............................................................
............................................................
................bbbbbbbbbbbbbbbbbbbbb.......................
..............bbdddddddddddddddddddddbbb....................
.............bddddddddddddddddddddddddddbb..................
.............bddddddddddddddddddddddddddbb..................
.............bdddddccccccccccccccccdddddbb..................
.............bdddddccccccccccccccccdddddbb..................
.............bdddddccccccccccccccccdddddbb..................
.............bdddddccccccccccccccccdddddbb..................
.............bddccc8888888888888888ccdddbb..................
.............bddccc1188188888888888ccdddbb..................
.............bddccc888818888fffff88ccdddbb..................
.............bddccc888818888fffff88ccdddbb..................
.............bddccc888818888fffff88ccdddbb..................
.............bddccc888818888fffff88ccdddbb..................
.............bddccc1188188888888888ccdddbb.f................
.............bddccc888888888fffff88ccdddbb.f................
.............bddccc8888888888888888ccdddbb.f................
.............bddccc8888888888888888ccdddbb.f................
.............bddccc8888888888888888ccdddbb.f................
.............bddccc8888888888888888ccdddbb.f................
..........111bddccc8888888888888888ccdddbb.f................
......8888811bddccc8888888888888888ccdddbb111111............
......8888811bdddddccccccccccccccccdddddbb111111............
......8888811bddddddddddddddddddddddddddbb111111............
......8888811bddddddddddddddddddddddddddbb111111............
......8888811bddddddddddddddddddddddddddbb111111............
......8888811bddddddddddddddddddddddddddbb111111............
...8888888811bdddddddddddddddddddddddddd77771111fffff.......
.aaaaa88888..cbbbbbbbbbbbbbbbbbbbbb7777777771111............
.afffa88888..cbbbbbbbbbbbbbbbbbbbbb7777777771111............
.afffa88888..cbbbbbbbbbbbbbbbbbbbbb7777777771111............
.afffa88888..cbbbbbbbbbbbbbbbbbbbbb7777777771111............
.aaaaa8888...bddddddddddbbbbbbdddaaaaaaa7777................
...aaa.......bdddddddddbbbbbbbbaaffffaaaaa7.................
.............bdddddddddb......baaffffaaaaa..................
.............bdddddddddb......baaffffaaaaa..................
.............bdddddddddb......baaffffaaaaa..................
.............bdddddddddb......baaffffaaaaa..................
.............bdddddddddb......baaaaaaaaaaa..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
.............bdddddddddb......bdddddddddbb..................
..............bbbbbbbbb........bbbbbbbbb....................
............................................................
............................................................
............................................................
............................................................
............................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
